In [1]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()


In [2]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
df = pd.DataFrame(iris.data,columns = iris.feature_names)

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
df["target"] = iris.target

In [8]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
dfs= df.drop(columns = "target")

In [26]:
X_train, X_test, y_train, y_test=train_test_split(dfs,df.target,test_size=0.25)

In [27]:
from sklearn.svm import SVC

In [28]:
model = SVC(kernel='rbf',C=30,gamma="auto")

In [29]:
model.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [32]:
model.score(X_test,y_test)  ##The problem is that the accuracy is changed again and again

1.0

In [33]:
#cross_validation_using_k_fold

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
cross_val_score(SVC(kernel = "linear",C = 1,gamma = "auto"),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [36]:
cross_val_score(SVC(kernel = "rbf",C = 1,gamma = "auto"),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [37]:
cross_val_score(SVC(kernel = "linear",C = 5,gamma = "auto"),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.93333333, 0.96666667, 1.        ])

In [38]:
cross_val_score(SVC(kernel = "rbf",C = 5,gamma = "auto"),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [39]:
#very manual method (the cross val)

In [43]:
#now we try using loops
import numpy as np

In [50]:
kernels = ["linear","rbf"]
c= [1,10,20]
average_scores = {}
for kval in kernels:
    for cval in c:
        cv_score = cross_val_score(SVC(kernel = kval,C=cval,gamma="auto"),iris.data,iris.target,cv=5)
        average_scores[kval+"    "+str(cval)]=np.mean(cv_score)
                       ##key                   #value

In [51]:
average_scores

{'linear    1': 0.9800000000000001,
 'linear    10': 0.9733333333333334,
 'linear    20': 0.9666666666666666,
 'rbf    1': 0.9800000000000001,
 'rbf    10': 0.9800000000000001,
 'rbf    20': 0.9666666666666668}

In [52]:
##for larger no of parameters the time complexity increases

In [53]:
#now use gridSearch

In [54]:
from sklearn.model_selection import GridSearchCV

In [71]:
clf = GridSearchCV(SVC(gamma="auto"),
                   {'C':[1,10,20],
                    'kernel':["rbf","linear"]},
                   cv=5,return_train_score=False) ##it does the same thing as cross validation but does all the manual work done in line50 manually

In [58]:
clf.fit(iris.data,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [59]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run

In [61]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [65]:
clf.cv_results_

{'mean_fit_time': array([0.00168324, 0.0015954 , 0.00319228, 0.00118394, 0.00157833,
        0.00139685]),
 'std_fit_time': array([0.00049818, 0.00048854, 0.00213043, 0.00038848, 0.00048632,
        0.0004757 ]),
 'mean_score_time': array([0.00100737, 0.00159788, 0.00240984, 0.00080914, 0.00120406,
        0.00079775]),
 'std_score_time': array([1.13035553e-05, 7.99061467e-04, 1.02292568e-03, 4.04721880e-04,
        4.12021808e-04, 3.98874354e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [66]:
df = pd.DataFrame(clf.cv_results_)

In [67]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.001683      0.000498         0.001007        0.000011        1   
1       0.001595      0.000489         0.001598        0.000799        1   
2       0.003192      0.002130         0.002410        0.001023       10   
3       0.001184      0.000388         0.000809        0.000405       10   
4       0.001578      0.000486         0.001204        0.000412       20   
5       0.001397      0.000476         0.000798        0.000399       20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [70]:
 df[["param_C", "param_kernel", "mean_test_score"]]


param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [72]:
##it also is so time consuming as it uses all permutations and combinations

In [73]:
#moreBetterWay

In [75]:
from sklearn.model_selection import RandomizedSearchCV

In [82]:
rs = RandomizedSearchCV(SVC(gamma="auto"),
                       {"kernel":["rbf","linear"],
                       "C":[1,10,20]},
                       cv=5,return_train_score=False,n_iter = 3)

In [83]:
rs.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=3,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [84]:
df = pd.DataFrame(rs.cv_results_)

In [85]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.002412      0.000510         0.001487        0.000446          rbf   
1       0.003010      0.000898         0.001635        0.000768       linear   
2       0.003590      0.001016         0.000995        0.000003       linear   

   param_C                         params  split0_test_score  \
0       20     {'kernel': 'rbf', 'C': 20}           0.966667   
1        1   {'kernel': 'linear', 'C': 1}           0.966667   
2       20  {'kernel': 'linear', 'C': 20}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.900000           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.966667        0.036515                2  
1         0.980000        0.016330                1  
2         0.966667        0.042164                3

In [86]:
df[["param_kernel","param_C","mean_test_score"]]

param_kernel  param_C  mean_test_score
0          rbf       20         0.966667
1       linear        1         0.980000
2       linear       20         0.966667

In [87]:
##now choosing the best model

In [89]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [103]:
model_params={
    "SVC":{
        "model":SVC(gamma="auto"),
        "params":{
            "kernel":["linear","rbf"],
            "C":[1,10,20]
        }
    },
    "randomforest":{
        "model":RandomForestClassifier(),
        "params":{
            "n_estimators":[1,5,10]
        }
    },
    "logisticregression":
    {
        "model": LogisticRegression(solver="liblinear",multi_class = "auto"),
        "params":{
            "C":[1,5,10]
        }
    }
    }

In [104]:
scores =[]
for model_name,mp in model_params.items():
    clf=GridSearchCV(mp["model"],mp["params"],cv=5,return_train_score=False)
    clf.fit(iris.data,iris.target)
    scores.append({
        "model":model_name,
        "best_score":clf.best_score_,
        "best_params":clf.best_params_
    })

C:\Users\Laraib\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\Laraib\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\Laraib\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\Laraib\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in ve

In [106]:
scores

[{'model': 'SVC',
  'best_score': 0.9800000000000001,
  'best_params': {'C': 1, 'kernel': 'linear'}},
 {'model': 'randomforest',
  'best_score': 0.9533333333333334,
  'best_params': {'n_estimators': 5}},
 {'model': 'logisticregression',
  'best_score': 0.9666666666666668,
  'best_params': {'C': 5}}]